### ISSUE TITLE
pdf toolkit 1.4 on ubuntu alfresco 5.1 community

### ISSUE THREAD

**Issue by pascalbeolet** [OrderOfTheBee/alfresco-pdf-toolkit#31] opened 2016-09-19 09:05 UTC
Helllo,
when I'm trying to apply_amps I got an 08190001 error saying that module.properties is missing both in repo and share
Any idea ?

**Comment by douglascrp** [comment] 2019-03-05 20:39
As I could not reproduce this, I am closing it.
Feel free to reopen it if needed.

**Closed by douglascrp** 2019-03-05 20:39 UTC
