### ISSUE TITLE
Alfresco 5.0 goes weird after encrypting file

### ISSUE THREAD

**Issue by essadek** [OrderOfTheBee/alfresco-pdf-toolkit#29] opened 2016-06-25 09:27 UTC
When encrypting a file and refreshing the page, I got blank page and Alfresco just display blank pages even when logout, the login page is blank, here the error stack:

```
2016-06-25 11:28:43,860 ERROR [org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl] [defaultAsyncAction2] Failed to execute asynchronous action: Action[ id=07b5082c-7762-4118-8b04-7e484ac7e9fe, node=workspace://SpacesStore/07b5082c-7762-4118-8b04-7e484ac7e9fe ]: 05250033 Failed to perform ImageMagick transformation: 
Execution result: 
   os:         Windows 8.1
   command:    F:\Alfresco\imagemagick\convert.exe F:\Alfresco\tomcat\temp\Alfresco\ImageMagickContentTransformerWorker_source_4765015421439093009.pdf[0] -auto-orient -resize "100x100>" F:\Alfresco\tomcat\temp\Alfresco\ImageMagickContentTransformerWorker_target_836707460362787561.png
   succeeded:  false
   exit code:  1
   out:        Error: /invalidfileaccess in pdf_process_Encrypt
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1 
   err:           **** This file requires a password for access.
   **** The file was produced by: 
   **** >>>> O/ô©!<ƒåPvL˜«mžò’˜¡fªGS•®¬öãtð‘ ÒÏÃŠÆí¨yüº¿?Í®³4ÁitGùÅã„Öì+?
'hz¿ Rò(¦;¸˜8¨Ø_îx„Ì <<<<
GPL Ghostscript 8.64: Unrecoverable error, exit co
org.alfresco.service.cmr.repository.ContentIOException: 05250034 Content conversion failed: 
   reader: ContentAccessor[ contentUrl=store://2016/6/25/11/28/387fbbe9-463b-40b3-b791-ba4880bc1aa8.bin, mimetype=application/pdf, size=443033, encoding=UTF-8, locale=en_US]
   writer: ContentAccessor[ contentUrl=store://F:\Alfresco\tomcat\temp\Alfresco\FailoverTransformer_intermediate_ProxyContentTransformer_1966396143428793070.png, mimetype=image/png, size=0, encoding=UTF-8, locale=en_GB]
   options: {use=doclib, contentReaderNodeRef=workspace://SpacesStore/4dff1caf-b7bf-4598-9811-0d71dca6a431, contentWriterNodeRef=null, sourceContentProperty=null, imageAutoOrient=true, targetContentProperty=null, commandOptions=, imageResizeOptions=ImageResizeOptions [width=100, height=100, maintainAspectRatio=true, percentResize=false, resizeToThumbnail=false, allowEnlargement=false], includeEmbedded=false}
   limits: {timeoutMs=120000}
    at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:332)
    at org.alfresco.repo.content.ContentServiceImpl.failoverTransformers(ContentServiceImpl.java:686)
    at org.alfresco.repo.content.ContentServiceImpl.transform(ContentServiceImpl.java:635)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.model.ml.MLContentInterceptor.invoke(MLContentInterceptor.java:129)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:46)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:159)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy39.transform(Unknown Source)
    at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable$1.doWork(AbstractTransformationRenderingEngine.java:439)
    at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable$1.doWork(AbstractTransformationRenderingEngine.java:430)
    at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
    at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable.call(AbstractTransformationRenderingEngine.java:429)
    at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable.call(AbstractTransformationRenderingEngine.java:404)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.alfresco.service.cmr.repository.ContentIOException: 05250033 Failed to perform ImageMagick transformation: 
Execution result: 
   os:         Windows 8.1
   command:    F:\Alfresco\imagemagick\convert.exe F:\Alfresco\tomcat\temp\Alfresco\ImageMagickContentTransformerWorker_source_4765015421439093009.pdf[0] -auto-orient -resize "100x100>" F:\Alfresco\tomcat\temp\Alfresco\ImageMagickContentTransformerWorker_target_836707460362787561.png
   succeeded:  false
   exit code:  1
   out:        Error: /invalidfileaccess in pdf_process_Encrypt
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1 
   err:           **** This file requires a password for access.
   **** The file was produced by: 
   **** >>>> O/ô©!<ƒåPvL˜«mžò’˜¡fªGS•®¬öãtð‘ ÒÏÃŠÆí¨yüº¿?Í®³4ÁitGùÅã„Öì+?
'hz¿ Rò(¦;¸˜8¨Ø_îx„Ì <<<<
GPL Ghostscript 8.64: Unrecoverable error, exit co
    at org.alfresco.repo.content.transform.magick.ImageMagickContentTransformerWorker.transformInternal(ImageMagickContentTransformerWorker.java:199)
    at org.alfresco.repo.content.transform.magick.AbstractImageMagickContentTransformerWorker.transform(AbstractImageMagickContentTransformerWorker.java:273)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:72)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy20.transform(Unknown Source)
    at org.alfresco.repo.content.transform.ProxyContentTransformer.transformInternal(ProxyContentTransformer.java:100)
    at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:250)
    ... 32 more
```

**Comment by essadek** [comment] 2016-06-25 10:46
The problem occurs only when refreshing the page right after the encryption.

**Comment by douglascrp** [comment] 2019-03-05 20:00
Not able to reproduce the issue with the current version.
Closing it

**Closed by douglascrp** 2019-03-05 20:00 UTC
